name: PR - Closed

on:
  pull_request:
    types: [ closed ]



jobs:
  delete-s3:
    name: Delete S3 Website
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Delete Website Bucket
        uses: danburtenshaw/s3-website-pr-action@v2
        with:
          bucket-prefix: "next-s3"
